In [1]:
# Install Python package - Numpy
# pip install numpy

In [2]:
# pip install numpy

In [3]:
import numpy as np

In [4]:
myList=[1,2,3,4,5]
stringList = [ "apple", "orange"]

In [5]:
print(myList)

[1, 2, 3, 4, 5]


In [6]:
type(myList)

list

In [7]:
# dir(np)

In [8]:
# help(np)

In [9]:
arr = np.array(myList)

In [10]:
print(arr)

[1 2 3 4 5]


In [11]:
print(type(arr))

<class 'numpy.ndarray'>


In [13]:
# shape of the array
arr.shape

(5,)

In [14]:
arr.size

5

In [27]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [22]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [23]:
type(arr)

numpy.ndarray

In [24]:
arr.shape

(3, 5)

In [25]:
arr.size

15

In [29]:
# Numpy array indexing

# Get the first element from the following array:

my_lst1=[1,2,3,4,5]
arr = np.array(my_lst1)

In [31]:
arr

array([1, 2, 3, 4, 5])

In [30]:
print(arr[0])

1


In [32]:
# Get the second element from the following array.

print(arr[1])

2


In [33]:
# Get third and fourth elements from the following array and add them.
print("The third elements is: ", arr[2]," and fourth elements is: ", arr[3])

The third elements is:  3  and fourth elements is:  4


In [44]:
# Access 2D array

my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr = np.array([my_lst1,my_lst2,my_lst3])
print(arr)
print(arr.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]
(3, 5)


In [35]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [40]:
arr[0,2]

3

In [41]:
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [45]:
# Access the element on the 2nd row, 5th column:
arr[1,4]

6

In [46]:
valArr = np.array([[1,2,3],[4,5,6]])    # Create a 2D array
# print the variable
# get shape
# get size
# index: first row First element
# index second row third element

In [49]:
# create  a 5*5 array
newArr= np.array([[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5],[11,12,13,14,15],[20,25,30,35,40]])
print("Print the Variable value : \n ",newArr, "\n")
print("The Shape of Variable :\n" ,newArr.shape, "\n")  # Prints "(2, 3)"\
print("The Size of Variable :\n", newArr.size, "\n")
#indexing using both row and column
print('2nd element on 3rd row: ',newArr[2,1])
print('1st element on 4th row: ',newArr[3,0])

Print the Variable value : 
  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [11 12 13 14 15]
 [20 25 30 35 40]] 

The Shape of Variable :
 (5, 5) 

The Size of Variable :
 25 

2nd element on 3rd row:  2
1st element on 4th row:  11


In [61]:
# Negative Indexing

mylist=[1, 2, 3, 4,5,6,7]
arr = np.array(mylist)

#print(arr)


valArr = np.array([[1,2,3],[4,5,6]])
print(valArr)

[[1 2 3]
 [4 5 6]]


In [73]:
valArr[1,2]

6

In [88]:
# NumPy Array Slicing -1D

mylist=[1, 2, 3, 4, 5, 6, 7, 8,9,10,11]

arr = np.array(mylist)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [76]:
# arr[start:end]
arr[0:5]

array([1, 2, 3, 4, 5])

In [78]:
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [81]:
arr[:5]

array([1, 2, 3, 4, 5])

In [83]:
arr[-3:-1]

array([8, 9])

In [84]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [85]:
# step
arr[::2]


array([1, 3, 5, 7, 9])

In [89]:
arr[1::3]

array([ 2,  5,  8, 11])

In [108]:
# Slicing 2-D Arrays
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

print(arr.shape)
print(arr)

(3, 5)
[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [114]:
arr[:,1:4]

array([[2, 3, 4],
       [3, 4, 5],
       [7, 6, 8]])

In [118]:
#Arange function

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
np.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [127]:
# Linspace
np.linspace(0,100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

# NumPy Data Types

Data Types in Python

By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"

integer - used to represent integer numbers. e.g. -1, -2, -3

float - used to represent real numbers. e.g. 1.2, 42.42

boolean - used to represent True or False.

complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

In [132]:
#arr = np.array([1, 2, 3, 4]) # Let numpy choose the datatype
arr = np.array([1.0, 2.0])

print(arr.dtype)

float64


In [134]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [135]:
arr = np.array(['apple', 'banana', 'cherry','bananacherry'])
print(arr.dtype)

<U12


In [4]:
import numpy as np
arr = np.array([1,2,3,4,5],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [13]:
arr = np.array([1,2,3,4,5])
print(arr)
#print(arr.dtype)

[1 2 3 4 5]
int32


In [16]:
# Slicing 2-D Arrays
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

#print(arr.shape)
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [17]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [7]:
arr = np.array([1,2,3,4,5],dtype=np.int64)
print(arr.dtype)

int64


In [10]:
arr = np.array([1,2,3,4,5],dtype=np.float32)
print(arr.dtype)

float32


In [11]:
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [25]:
# Array Math
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])



In [26]:
print(x)
print("**")
print(y)

[[1 2]
 [3 4]]
**
[[5 6]
 [7 8]]


In [27]:
x+y

array([[ 6,  8],
       [10, 12]])

In [28]:
x-y

array([[-4, -4],
       [-4, -4]])

In [29]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [30]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [31]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [32]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [33]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [34]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [35]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8],[9,10]], dtype=np.float64)

In [36]:
x.shape

(2, 2)

In [38]:
y.shape

(3, 2)

In [39]:
np.add(x,y)

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [40]:
np.subtract(x,y)

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [41]:
np.divide(x,y)

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [43]:
x

array([[1., 2.],
       [3., 4.]])

In [42]:
np.exp(x)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [44]:
np.log(x)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [45]:
np.cos(x)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [46]:
np.tan(x)

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128]])

In [52]:
# Floor, Ceil, Round
x = np.array([[1.5,2.6],[3.1,4.9]], dtype=np.float64)


In [54]:
x

array([[1.5, 2.6],
       [3.1, 4.9]])

In [49]:
np.floor(x)

array([[1., 2.],
       [3., 4.]])

In [50]:
np.ceil(x)

array([[2., 3.],
       [4., 5.]])

In [53]:
np.round(x)

array([[2., 3.],
       [3., 5.]])

In [55]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
z = np.array([[9,10],[11,12]], dtype=np.float64)

In [56]:
x*y*z

array([[ 45., 120.],
       [231., 384.]])

In [57]:
np.multiply(x,y,z)

array([[ 5., 12.],
       [21., 32.]])

In [58]:
import numpy as np
x = np.array([[1,2],[3,4],[5,6]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [59]:
v.dot(w)

219

In [60]:
np.dot(v,w)

219

In [61]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
x.shape

(3, 2)

In [39]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [42]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
np.sum(x,axis=0)

array([12, 15, 18])

In [45]:
np.sum(x,axis=1)

array([ 6, 15, 24])

In [ ]:
# axis=0/1 0:column  1:row 

In [4]:
np.sum(x,axis=0) # column wise sum

array([12, 15, 18])

In [5]:
np.sum(x,axis=1) # Row wise sum

array([ 6, 15, 24])

In [71]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
x.T # transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#### Agenda for March 24

In [9]:
#### Numpy
############################
# NumPy Array Copy vs View
# NumPy Array Reshaping
# Flattening the arrays
# Iterating Arrays
# Iterating 2-D Arrays
# Joining NumPy Arrays
############################


#### Pandas
## Intro to Pandas

In [11]:
# NumPy Array Copy vs View
arr = np.array([1, 2, 3, 4, 5])
x = arr

In [12]:
print(arr)

[1 2 3 4 5]


In [13]:
print(x)

[1 2 3 4 5]


In [19]:
arr[0] =100

In [20]:
print(arr)

[100   2   3   4   5]


In [21]:
print(x)

[100   2   3   4   5]


In [23]:
x[1] =200

In [24]:
print(x)

[100 200   3   4   5]


In [25]:
print(arr)

[100 200   3   4   5]


In [30]:
# NumPy Array Copy 
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()

In [31]:
print(arr)

[1 2 3 4 5]


In [32]:
print(x)

[1 2 3 4 5]


In [33]:
arr[0] =100

In [34]:
print(arr)


[100   2   3   4   5]


In [35]:
print(x)

[1 2 3 4 5]


In [36]:
x[1] =100

In [37]:
print(x)

[  1 100   3   4   5]


In [38]:
print(arr)

[100   2   3   4   5]


In [53]:
# NumPy Array Reshaping
arr = np.arange(1,13)
arr.shape

(12,)

In [65]:
arr_new= arr.reshape(4,5)

ValueError: cannot reshape array of size 12 into shape (4,5)

In [64]:
arr_new # 1D-----> 2D

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [67]:
# Flattening the arrays
# 2D-----> 1D
arr_new.reshape(-1)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [80]:
# Iterating Arrays
arr = np.arange(1,7).reshape(3,2)

In [81]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [82]:
for x in arr:
    print(x)

[1 2]
[3 4]
[5 6]


In [83]:
# Joining NumPy Arrays # 1D
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

In [84]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [90]:
#Join two 2-D arrays along rows (axis=1):

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

np.concatenate((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [87]:
arr1

array([[1, 2],
       [3, 4]])

In [88]:
arr2

array([[5, 6],
       [7, 8]])